### PR TITLE
CC-16681: Adjusted address2 field to be optional instead of required.

### PR DESCRIPTION
**Pull request by michbeck**
- Developer(s): @michbeck

- Ticket: https://spryker.atlassian.net/browse/CC-16681

- Release Group: https://release.spryker.com/release-groups/view/4127

- PR Overview: https://release.spryker.com/release/pull-request-eco/AvalaraTax/19

- merge: squash

#### Release Table

   Module                | Release Type         | Constraint Updates         |
   :--------------------- | :------------------------ | :--------------------- |
   AvalaraTax            | patch  |                       |

-----------------------------------------

##### Change log

Adjustments
- Adjusted `AvalaraTaxFacade::calculateTax()` so it does not require `address2` value instead of throwing exception while not specified.
- Adjusted `AvalaraItemTaxRateCalculatorPlugin::recalculate()` so it does not require `address2` value instead of throwing exception while not specified.
- Introduced `Quote.store` transfer property.
- Introduced `Quote.items` transfer property.
- Introduced `Stock.name` transfer property.
- Introduced `StockProduct.sku` transfer property.

### CODE REVIEW

**Comment by dereuromark** [comment]
I dont think a skip is OK if those are functional issues, they need to be released.

**Review by herasimenko1987 — APPROVED** [review]

**Comment by dereuromark** [comment]
Why is this not a patch?

**Review by AsonUnique — APPROVED** [review]

**Comment by DmitryLymarenko** [comment]
1. ~not a patch but minor~ I didn't notice that this module is still in beta version
2. `merge: merge` -> `merge: squash`
3. PR overview link is missing
4. Release group should be linked to a ticket
5. `Fixes` section name is wrong. It's more `adjustments`
6. `AvalaraItemTaxRateCalculatorPlugin` was impacted by these changes, but not mentioned

**Comment by dereuromark** [comment]
If the Transfer fields have been missing I dont see a reason to escalate to a minor. What's the reason?

**Comment by dereuromark** [comment]
Please note: it must be **patch** above as this is a semantic minor, you otherwise release a major here which is not acceptable
I fixed the table now as I suggested before.
So yes, it is a minor, but a semantic one!

**Comment by DmitryLymarenko** [comment]
thank you for your attention
I missed that this module is still in beta

**Review by DmitryLymarenko — APPROVED** [review]

**Pull request merged**
